Planetshakers.Events.Mvc/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Planetshakers.Events.Mvc.Filters;
using Planetshakers.Events.Mvc.Models;
using Planetshakers.Business.External.Events;
using System.Windows.Forms;
using System.Data.Entity.SqlServer;
using static Planetshakers.Events.Mvc.Helpers.VoucherExtensions;
using Planetshakers.Events.Mvc.Helpers;
using log4net;
using System.Security.Cryptography;

namespace Planetshakers.Events.Mvc.Controllers
{
    public class EventsController : Controller
    {
        private ILog pxlogger = LogManager.GetLogger("GeneralLogger");

        public const string MSG_USR_NOT_AUTHENTICATED = "There was an error while authenticating your e-mail / password. Please try again.";

        [AllowAnonymous]
        public ActionResult Index(string returnUrl)
        {
            //For SSO use
            string PSCookies = Planetshakers.Business.MWebMain.PSCookieAliveValue(Request);

            if (PSCookies != string.Empty)
            {
                Planetshakers.Business.MWebMain.LogMessage("Planetshakers cookie has found in register logon.");
                LoginWithCookie(PSCookies);
            }

            var model = new EventIndexModel()
            {
                Events = Lists.RetrieveEvents(getContactID(), false).Where(x => x.visible).ToList()
            };

            if (Session["Contact"] != null)
            {
                var contact_id = getContactID();
                using (PlanetshakersEntities entity = new PlanetshakersEntities())
                {
                    model.Barcodes = (from er in entity.Events_Registration
                                      join ev in entity.Events_Venue
                                          on er.Venue_ID equals ev.Venue_ID
                                      where er.Contact_ID == contact_id && DateTime.Today <= ev.ConferenceEndDate
                                      select new Registration
                                      {
                                          Registration_ID = er.Registration_ID,
                                          Contact_ID = er.Contact_ID,
                                          Barcode = "https://www.barcodesinc.com/generator_files/image.php?code=" + SqlFunctions.StringConvert((double)er.Registration_ID).Trim() + "&style=197&type=C128B",
                                          Venue_ID = er.Venue_ID
                                      }).ToList();


                    // Retrieve all event details
                    ViewBag.ReturnUrl = returnUrl;
                    ViewBag.contact_id = contact_id;

                    return View(model);
                }
            }
            else
            {
                ViewBag.ReturnUrl = returnUrl;

                return View(model);
            }

        }

        public void LoginWithCookie(string PSCookies)
        {
            using (PlanetshakersEntities entity = new PlanetshakersEntities())
            {
                int contact_id = Convert.ToInt32(PSCookies);
                Common_Contact contact = (from cc in entity.Common_Contact where cc.Contact_ID == contact_id select cc).FirstOrDefault();

                try
                {
                    if (contact != null)
                    {
                        Common_ContactExternal ce = (from cce in entity.Common_ContactExternal
                                                     where cce.Contact_ID == contact.Contact_ID
                                                     select cce).FirstOrDefault();

                        if (ce == null)
                        {
                            // create new common_contactExternalEvents
                            //var new_contact_event = new Common_ContactExternalEvents();
                            //new_contact_event.EmergencyContactName = "";
                            //new_contact_event.EmergencyContactPhone = "";
                            //new_contact_event.EmergencyContactRelationship = "";
                            //new_contact_event.MedicalInformation = "";
                            //new_contact_event.MedicalAllergies = "";
                            //new_contact_event.AccessibilityInformation = "";
                            //new_contact_event.EventComments = "";

                            // create new external contact
                            var new_external_contact = new Common_ContactExternal();
                            new_external_contact.ChurchAddress1 = "";
                            new_external_contact.ChurchAddress2 = "";
                            new_external_contact.ChurchCountry_ID = null;
                            new_external_contact.ChurchEmail = "";
                            new_external_contact.ChurchName = "";
                            new_external_contact.ChurchNumberOfPeople = "";
                            new_external_contact.ChurchPhone = "";
                            new_external_contact.ChurchPostcode = "";
                            new_external_contact.ChurchState_ID = null;
                            new_external_contact.ChurchStateOther = "";
                            new_external_contact.ChurchSuburb = "";
                            new_external_contact.ChurchWebsite = "";
                            new_external_contact.Denomination_ID = 49;
                            new_external_contact.SeniorPastorName = "";
                            new_external_contact.LeaderName = "";
                            new_external_contact.Deleted = false;
                            new_external_contact.Inactive = false;

                            entity.Common_ContactExternal.Add(new_external_contact);

                            contact.Common_ContactExternal = new_external_contact;

                            entity.SaveChanges();
                        }

                        Authenticator.Contact c = new Authenticator.Contact();
                        c.Id = contact.Contact_ID;
                        c.FirstName = contact.FirstName;
                        c.LastName = contact.LastName;
                        c.Email = contact.Email;

                        // Store contact information on session
                        Session["Contact"] = c;
                    }
                    else
                    {
                        ViewBag.Error = MSG_USR_NOT_AUTHENTICATED;
                    }

                }
                catch (Exception ex)
                {
                    ViewBag.Error = MSG_USR_NOT_AUTHENTICATED;
                    throw ex;
                }
            }
        }

        [PSAuthorize]
        public ActionResult Registrations(int id, string returnUrl)
        {
            using (PlanetshakersEntities context = new PlanetshakersEntities())
            {

                ViewBag.ReturnUrl = returnUrl;

                // Retrieve logged in contact from session
                var contact = (Planetshakers.Events.Mvc.Authenticator.Contact)Session["Contact"];

                var model = new EventSummaryModel()
                {
                    Contact_ID = contact.Id,
                    SelectedEvent = Lists.RetrieveEvents(getContactID(), false).Where(e => e.venueID == id).First(),
                    Group = new EventGroup(contact.Id),
                    basicDetails = new BasicDetailsPartialModel(),
                    credentialDetails = new CredentialDetailsPartialModel(),
                    personalDetails = new PersonalDetailsPartialModel(),
                    contactDetails = new ContactDetailsPartialModel(),
                    churchDetails = new ChurchDetailsPartialModel(),
                    churchInvolvementDetails = new ChurchInvolvementPartialModel()
                    {
                        AvailableCInvolvement = Lists.getChurchInvolvement(null)
                    },
                    emergencyDetails = new EmergencyDetailsPartialModel(),
                    addOnModel = new AddOnModel()
                    {
                        Contact_ID = contact.Id,
                        Venue_ID = id
                    }
                };
                model.SelectedEvent.totalCost = model.SelectedEvent.totalCost + model.SelectedEvent.addOnPayments;
                model.SelectedEvent.totalPayment = model.SelectedEvent.totalPayment + model.SelectedEvent.addOnPayments;
                
                var payments = (from gp in context.Events_GroupPayment
                                join pt in context.Common_PaymentType on gp.PaymentType_ID equals pt.PaymentType_ID
                                join ps in context.Common_PaymentSource on gp.PaymentSource_ID equals ps.PaymentSource_ID
                                join cc in context.Common_Contact on gp.GroupLeader_ID equals cc.Contact_ID
                                where gp.GroupLeader_ID == contact.Id && gp.Conference_ID == model.SelectedEvent.id
                                && (gp.ExpiredIntent != true || gp.ExpiredIntent == null) && gp.PaymentCompleted == true
                                select new Payment
                                {
                                    ID = gp.GroupPayment_ID,
                                    ContactName = cc.FirstName + " " + cc.LastName,
                                    PaymentType_ID = gp.PaymentType_ID,
                                    PaymentType = pt.PaymentType,
                                    PaymentSource_ID = gp.PaymentSource_ID,
                                    PaymentSource = ps.PaymentSource,
                                    TransactionRef = gp.CCTransactionRef,
                                    Amount = gp.PaymentAmount,
                                    StartDate = gp.PaymentStartDate,
                                    CompletedDate = gp.PaymentCompletedDate,

Planetshakers.Events.Mvc/Views/Events/Index.cshtml
@model Planetshakers.Events.Mvc.Models.EventIndexModel
@using Planetshakers.Events.Mvc.Models;

@{
    ViewBag.Title = "Believe";
    ViewBag.ButtonRegister = "Apply Now";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@section scripts {
    @Scripts.Render("~/bundles/planetshakers/events/registration")
}

<div class="row" id="indexloaded">
    <div class="col-12 px-4">
        <!-- Automated Events sequencing and launching ordered by Events_Conference.SortOrder -->
        @foreach (var e in Model.Events)
        {
            <div class="event-row">
                <div class="row">
                    <div class="col-lg-12">
                        <img class="event-index-banner" src="@e.banner_img" alt="@e.name">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-12 pb-2">
                        <div class="event-info">
                            <h4>@e.name</h4>
                            <span class="subheader">@e.date<br /></span>
                            <span class="subheader">@e.location<br /></span>
                        </div>
                    </div>
                    @*removed barcode*@
                    <div class="col-lg-3 col-md-12 pb-2"></div>

                    <div class="col-lg-3 col-md-12 pb-2">
                        <div class="mx-1">
                            @if (e.rego_categories.Any())
                            {
                                <div class="">
                                    @if (e.allocatedToUser || e.boughtByUser)
                                    {
                                        if (e.ApplicationProgress == 1 || e.ApplicationProgress == 5)
                                        {
                                            <a href="@Url.Action("ApplicationForm", "Application", new { id = e.venueID })" class="btn btn-grey btn-block">Complete Application</a>
                                        }
                                        else if (e.ApplicationProgress == 2)
                                        {
                                            <a href="#" class="btn btn-grey btn-block">Processing Application</a>
                                        }
                                        //after the application is approved or denied
                                        else if (e.ApplicationProgress == 3)
                                        {
                                            <a href="@Url.Action("TripDetails", "TripDetails", new { id = e.venueID })" class="btn btn-black btn-block">Trip Details</a>
                                            <a href="@Url.Action("Registrations", "Events", new { id = e.venueID })" class="btn btn-grey btn-block">Payment Details</a>                                            
                                        }
                                        else if (e.ApplicationProgress == 6)
                                        {
                                            <a href="#" class="btn btn-grey btn-block">No Longer Attending</a>
                                            <a href="@Url.Action("Registrations", "Events", new { id = e.venueID })" class="btn btn-grey btn-block">Payment Details</a>
                                        }
                                        else
                                        {
                                            <a href="#" class="btn btn-grey btn-block">Application Denied</a>
                                        }
                                        @*<a href="@Url.Action("Registrations", "Events", new { id = e.venueID })" class="btn btn-grey btn-block">View Registrations</a>*@

                                        <!-- new outstanding balance payment button here -->
                                    }
                                    else if (e.remainingRegosVenue <= 0)
                                    {
                                        <a href="@Url.Action("Register", "Events", new { id = e.venueID })" class="btn btn-black btn-block disabled">Registration Full</a>

                                    }
                                    else
                                    {
                                        <a href="@Url.Action("Register", "Events", new { id = e.venueID })" class="btn btn-black btn-block">@ViewBag.ButtonRegister</a>
                                    }
                                </div>
                            }
                            else
                            {
                                <div>
                                    @*<a href="@Url.Action("Registrations", "Events", new { id = e.venueID })" class="btn btn-grey btn-block">View Registrations</a>*@
                                    <a href="#" class="btn btn-black btn-block">Registrations Closed</a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-3.7.1.min.js")"></script>

<script type="text/javascript">

    function ClickAddOnBtn(Venue_ID) {
        $.ajax({
            cache: false,
            type: "POST",
            url: "Events/AddOns",
            data: { "Venue_ID": Venue_ID },
            success: function (json) {
                console.log(json)
                $("#AddOnModalBody").html(json)
                $("#AddOnsModal").modal("show")

            },
            error: function () {
                alert("Unable to open window.");
            }
        });
    }

</script>

Planetshakers.Events.Mvc/Views/Events/Register.cshtml
@model Planetshakers.Events.Mvc.Models.EventRegisterModel
@using Planetshakers.Business.External.Events;
@using Planetshakers.Events.Mvc.Controllers;
@{
    ViewBag.Title = "Believe | " + Model.SelectedEvent.name;
    ViewBag.ButtonRegister = "Register";
    ViewBag.ButtonSponsor = "Sponsor";
    ViewBag.CalculatedTotalLabel = "Calculated total";
    ViewBag.CalculatedTotalInputName = "total";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<int> reg_IDs = new List<int>();
}
@section scripts {
    @Scripts.Render("~/bundles/planetshakers/events/register")
}

<script>
    var id = '@Model.SelectedEvent.id';


</script>

<div class="row mx-0">
    <div class="col-lg-12">
        <div class="event-reg-container">
            <div class="row event-banner-container">
                <div class="col-lg-12">
                    <img class="event-banner" src="@(Url.Content(Model.SelectedEvent.banner_img))" alt="">
                </div>
            </div>
            <div class="row mx-0 px-2">
                <div class="col-sm-12">
                    <div class="event-summary border-bottom">
                        <h3>@Model.SelectedEvent.name</h3>
                        <h5 class="subheader">@Model.SelectedEvent.date</h5>
                        <h5 class="subheader">@Model.SelectedEvent.location</h5>
                    </div>

                    @if (Model.SelectedEvent.rego_categories.Any())
                    {
                        <form class="form-group">
                            @Html.Hidden("VenueId", Model.VenueId)
                            @Html.Hidden("Event_ID", Model.SelectedEvent.id)
                            <div class="new-rego-header">
                                <h4>New Application</h4>
                            </div>

                            <div class="rego-categories">
                                @foreach (RegistrationCategory regCat in Model.SelectedEvent.rego_categories)
                                {
                                    if (!reg_IDs.Contains((int)regCat.group_id))
                                    {
                                        reg_IDs.Add((int)regCat.group_id);
                                        <a id="@(regCat.group_id)_RegisterCategoryButton" href="#" type="submit" class="btn reg-category-btn secondary">Application</a>
                                    }
                                }
                            </div>
                            <br />
                            @foreach (RegistrationCategory regCat in Model.SelectedEvent.rego_categories)
                            {
                                <input type="hidden" class="form-control" id="@(regCat.group_id)_QuantityPurchased" value="@(Model.registrationCount((int)regCat.group_id))" />
                                <div class="rego-groups" id="@(regCat.group_id)_RegistrationGroup">

                                    <table class="table-bordered expand" data-sort="false">
                                        <thead class="table-active">
                                            <tr>
                                                <th>Registration Type</th>
                                                <th data-hide="phone">Price</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (RegistrationType regType in regCat.rego_types)
                                            {
                                                <tr>
                                                    <td>@(regType.name)</td>
                                                    <td>@(Model.SelectedEvent.currency) <span id="@(regType.id)_Cost">@(regType.cost)</span></td>
                                                    <td><button onclick="OpenTnCmodal(@regType.id, @regCat.group_id, event)" style="color: white;" class="btn btn-block btn-primary">Apply</button></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                    <br />
                                    @*<div class="row mx-0">
                                            <div class="col-lg-12 px-0">
                                                <strong>Please Note:</strong>
                                            </div>
                                            <div class="col-sm-11 offset-sm-1 px-0">
                                                <p>
                                                    <input id="TermsAndConditionsCheckbox" type="checkbox" onclick="termsAndConditionsClicked()" style="margin-right: 5px" />
                                                    I hereby have read, accept and agree to the <a href="@Url.Action("TermsAndConditions", "Events")" target="_blank">terms and conditions</a>.
                                                </p>
                                            </div>
                                        </div>*@

                                </div>
                            }
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div id="TermsAndConditionsModal" class="modal fade text-black-100" aria-labelledby="editrego" tab-index="-1" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div id="TermsAndConditionsContent">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Terms and Conditions</h5><br />
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row" style="max-height: 400px; overflow: auto">
                        <div class="col-lg-12">
                            <div class="tab-content">
                                <div class="tab-pane active show update-background px-2 px-lg-4" id="TnC_Content">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <br />
                            <input id="TermsAndConditionsCheckbox" type="checkbox" onclick="termsAndConditionsClicked()" style="margin-right: 5px" />
                            By ticking this checkbox, I acknowledge that I have read, understand and agree to the Terms and Conditions and to be added to the Believe Mission Trip mailing list.
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" id="SubmitBtn" onclick="RegisterFor()" disabled>Submit</button>
                    <button class="btn btn-primary" data-dismiss="modal" aria-label="Close">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function checkEnter(e) {
        e = e || event;
        var txtBox = /textarea/i.test((e.target || e.srcElement).tagName);
        return txtBox || (e.keyCode || e.which || e.charCode || 0) !== 13;
    }

    document.querySelector('form').onkeypress = checkEnter;

    function termsAndConditionsClicked() {
        var agreed = document.getElementById("TermsAndConditionsCheckbox").checked
        if (agreed) {
            $('#SubmitBtn').prop('disabled', false);
        } else {
            $('#SubmitBtn').prop('disabled', true);
        }
    }

    function OpenTnCmodal(RegoType_ID, group_ID, event) {
        event.preventDefault();
        var Event_ID = $("#Event_ID").val();
        $.ajax({
            type: 'POST',
            url: '/Events/TermsAndConditions',
            data: { "Event_ID": Event_ID },
            dataType: 'json',
            success: function (json) {
                $("#TnC_Content").html(json.content);
                $("#SubmitBtn").attr("onclick", "RegisterFor(" + RegoType_ID + ", " + group_ID + ", event)")
                $("#TermsAndConditionsModal").modal("show");
            },
            error: function (error) {
                console.log('Unable to apply');
            }
        });
    }

    function RegisterFor(RegoType_ID, group_ID, event) {
        event.preventDefault();
        var returnUrl = '';
        if ($('#returnurl').val() !== null) {
            returnUrl = '?returnUrl=' + $('#returnurl').val();
        }
        var venue_id = $('#VenueId').val();
        var agreed = document.getElementById("TermsAndConditionsCheckbox").checked

        if (!agreed) {
            alert("Please read and agree to the terms and conditions")
        } else {
            $.ajax({
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                url: '/Events/SubmitRegistration' + returnUrl,
                data: JSON.stringify({ "RegistrationType_ID": RegoType_ID, "group_ID": group_ID, "venue_id": venue_id }),
                dataType: 'json',
                success: function (response) {
                    if (response.isSuccess) {
                        window.location.href = response.value;
                    } else {
                        alert("Failed! || " + response.value);
                    }
                },
                error: function (error) {
                    console.log('failed');
                }
            });
        }

    }

</script>

Planetshakers.Events.Mvc/Views/Events/TermsAndConditions.cshtml
@{
    ViewBag.Title = "Believe | Terms And Conditions";
}

<div class="row">
    <div class="col-md-9">
        <div class="row">
            <div style="margin-left : 14px" class="col-lg-12 border-bottom">
                <h2>Terms and Conditions</h2>
            </div>
        </div>
        <div class="row terms-conditions-container">
            <div style="margin-left : 14px" class="col-lg-12">
                @*<strong>Terms and Conditions</strong>*@
                <div>
                    By completing this online registration, you acknowledge and agree to the terms and conditions below.
                </div>
                <br />

                <div>
                    <u>1. Confirmation of Acceptance for Mission Trip</u>
                </div>
                <div>
                    You acknowledge and understand that by completing this online registration, you are applying to be a part of the Believe mission trip. Your application will be assessed and you will be notified of the outcome via email within two weeks of application.
                </div>
                <div>
                    If you are accepted, you must pay the remainder of the registration fee in accordance with clause 2 below.
                </div>
                <div>
                    If you are not accepted, you acknowledge that your deposit payment will not be refundable.
                </div>

                <br />
                <div>
                    <u>2. Payment</u>
                </div>
                <div>
                    Where you are accepted to be a part of the Mission Trip, you agree to pay <u>$2,700.00</u> to cover the costs of your participation in the Mission Trip (i.e. flights, accommodation, transport and food), in accordance with the payment deadlines below:
                </div>
                <div>
                    <ul>
                        <li>On registration - $50.00 (non-refundable reposit);</li>
                        <li>1st Deadline - 10th April 2022 - $1,200</li>
                        <li>2nd Deadline - 1st May 2022 - $850</li>
                        <li>Final Deadline - 15th May 2022 - $600</li>
                    </ul>
                </div>
                <div>
                    All amounts are in AUD and are subject to GST.
                </div>
                <br />

                <div>
                    <u>3. Amendment / Change Fee</u>
                </div>
                <div>
                    Any amendment in relation to your travel for the mission trip (i.e. extension requests, flight changes, name changes etc.) made after 10th April 2022 will incur a service fee of $75 per person <span style="color: red">plus</span> 10% GST. This is in addition to any supplier fees or charges associated with the change.
                </div>
                <br />

                <div>
                    <u>4. Cancellation Policy</u>
                </div>
                <div>
                    If you choose to cancel you registration for any reason, you understand that the full deposit is non-refundable and the following will apply:
                    <ul>
                        <li>Up to <span style="color: red">10th April 2022</span>, $1000 will be forfeited and any remaining amount paid will be refunded;</li>
                        <li>From <span style="color: red">11th April to 30th April 2022</span>, $1250 will be forfeited and any remaining amount paid will be refunded.</li>
                        <li>From <span style="color: red">1st May to 22nd May 2022</span>, $2,100 will be forfeited and any remaining amount paid will be refunded.</li>
                        <li>From <span style="color: red">23rd May 2022</span> onwards, the full amount of $2,700 will be forfeited and no refund will be given.</li>
                    </ul>
                </div>
                <br />

                <div>
                    <u>5. Transfer of Registrations Policy</u>
                </div>
                <div>
                    Individual registrations can be transferred to another individual to attend the mission trip by putting a request in writing to subject to additional costs that may be incurred in amending/cancelling flight tickets.
                </div>
                <div>
                    However, you may not transfer this registration from this mission trip to a different mission trip.
                </div>
                <br />

                <div>
                    <u>6. Other Terms and Conditions</u>
                </div>
                <div>
                    Where you are accepted to be a part of the Mission Trip, you acknowledge and understand that:
                    <ul>
                        <li>You may be required to attend briefings and training sessions prior to the mission trip;</li>
                        <li>You may be required to comply with policies and procedures in respect of the mission trip;</li>
                        <li>You may be required to complete additional forms in respect of the mission trip (e.g. media waiver, medical consent etc).</li>
                    </ul>
                </div>
                <div>
                    You also acknowledge and understand that failure by you to comply with the above may result in your removal from the Mission Trip. In such case, you will be deemed to have cancelled and the cancellation policy above will apply.
                </div>
            </div>
        </div>
    </div>
</div>